backend:
  name: github
  repo: DeuxAxios/hackfate
  branch: master

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "content"
    label: "Content Blocks"
    label_singular: "Content Block"
    file: "_data/content.json" # All content will be stored in this single file
    fields:
      - name: "blocks"
        label: "Content Blocks"
        label_singular: "Block"
        widget: "list"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Text", name: "text", widget: "markdown"}
          - {label: "Media", name: "media", widget: "image", required: false}